export const mockLedgerData = {
  tenants: {
    alpha: {
      tenantId: "alpha",
      businessName: "Alpha Global Trading LLC",
      baseCurrency: "USD",
      locale: "en-US",
      themeColor: "#1e3a8a",
    },
    beta: {
      tenantId: "beta",
      businessName: "Beta Retail Solutions Ltd",
      baseCurrency: "NGN",
      locale: "en-NG",
      themeColor: "#065f46",
    },
  },
  transactions: [
    {
      id: "tx_001",
      tenantId: "alpha",
      amountInMinor: 125050,
      type: "CREDIT",
      status: "SUCCESSFUL",
      narration: "Payout from Stripe",
      createdAt: "2026-06-20T14:30:00Z",
    },
    {
      id: "tx_002",
      tenantId: "alpha",
      amountInMinor: 4200,
      type: "DEBIT",
      status: "SUCCESSFUL",
      narration: "AWS Cloud Infrastructure Bill",
      createdAt: "2026-06-22T09:15:22Z",
    },
    {
      id: "tx_003",
      tenantId: "beta",
      amountInMinor: 8500000,
      type: "CREDIT",
      status: "SUCCESSFUL",
      narration: "Bulk Inventory Purchase Settlement",
      createdAt: "2026-06-23T18:45:10Z",
    },
    {
      id: "tx_004",
      tenantId: "beta",
      amountInMinor: 155045,
      type: "DEBIT",
      status: "FAILED",
      narration: "Interswitch Gateway Dispatch Fee",
      createdAt: "2026-06-24T02:10:00Z",
    },
    {
      id: "tx_005",
      tenantId: "alpha",
      amountInMinor: 1999,
      type: "DEBIT",
      status: "PENDING",
      narration: "Github Enterprise Subscription",
      createdAt: "2026-06-24T04:00:15Z",
    },
  ],
} as const;
